~/bayesian/dashboard/repositories/fabric8-analytics-scaler ~/bayesian/dashboard/repositories/fabric8-analytics-scaler
Already using interpreter /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/venv/bin/python3
Using base prefix '/usr'
  No LICENSE.txt / LICENSE found in source
New python executable in /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-scaler/venv/bin/python3
Not overwriting existing python script /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-scaler/venv/bin/python (you must use /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-scaler/venv/bin/python3)
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/venv/bin/python3
Requirement already satisfied: pyflakes in ./venv/lib/python3.6/site-packages (2.1.1)
----------------------------------------------------
Checking source files for common errors in following
directories:
.
----------------------------------------------------

./tools/check_python_version.py
    Pass
./sqs_status.py
    Pass
~/bayesian/dashboard/repositories/fabric8-analytics-scaler
All checks passed for 2 source files
