~/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-github-refresh-cronjob ~/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-github-refresh-cronjob
created virtual environment CPython3.6.10.final.0-64 in 152ms
  creator CPython3Posix(dest=/home/msawood/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-github-refresh-cronjob/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/msawood/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
Requirement already satisfied: pyflakes in ./venv/lib/python3.6/site-packages (2.2.0)
----------------------------------------------------
Checking source files for common errors in following
directories:
tests
tools
src
----------------------------------------------------

tests/conftest.py
    Pass
tests/test_github_refresh.py
    Pass
tools/check_python_version.py
    Pass
src/github_refresh.py
    Pass
----------------------------------------------------
Checking following source files for common errors:

----------------------------------------------------

~/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-github-refresh-cronjob
All checks passed for 4 source files
