~/bayesian/dashboard/repositories/fabric8-analytics-api-gateway ~/bayesian/dashboard/repositories/fabric8-analytics-api-gateway
Using base prefix '/usr'
New python executable in /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-api-gateway/venv/bin/python3
Not overwriting existing python script /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-api-gateway/venv/bin/python (you must use /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-api-gateway/venv/bin/python3)
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/venv/bin/python3
Requirement already satisfied: pyflakes in ./venv/lib/python3.6/site-packages (2.0.0)
----------------------------------------------------
Checking source files for common errors in following
directories:
gateway
tests
tools
----------------------------------------------------

gateway/auth.py
    Pass
gateway/__init__.py
    Pass
gateway/api_v1.py
    Pass
gateway/errors.py
    Pass
gateway/defaults.py
    Pass
tests/test_errors.py
    Pass
tests/test_api_v1.py
    Pass
tests/test_auth.py
    Pass
tests/test_defaults.py
    Pass
tools/check_python_version.py
    Pass
~/bayesian/dashboard/repositories/fabric8-analytics-api-gateway
All checks passed for 10 source files
