~/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth ~/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth
----------------------------------------------------
Running Python linter against following directories:
fabric8a_auth
tests
tools
----------------------------------------------------

created virtual environment CPython3.6.10.final.0-64 in 368ms
  creator CPython3Posix(dest=/home/msawood/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/msawood/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
Requirement already satisfied: pycodestyle in ./venv/lib/python3.6/site-packages (2.5.0)
fabric8a_auth/__init__.py
    Pass
fabric8a_auth/errors.py
    Pass
fabric8a_auth/auth.py
    Pass
tests/test_utility_functions.py
    Pass
tests/test_token_handling.py
    Pass
tests/__init__.py
    Pass
tests/test_errors_class.py
    Pass
tools/check_python_version.py
    Pass

----------------------------------------------------
Running Python linter against selected files:
setup.py
----------------------------------------------------
setup.py
    Pass
All checks passed for 9 source files
~/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth
